set -e

make

app=./build/app

echo "test: making database"
$app ./test.db c

echo "test: adding row 1"
$app ./test.db s 1 kingofmongeese some_email

echo "test: listing db"
$app ./test.db l

echo "test: adding some wild data"
$app ./test.db s 2 goofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofy email
$app ./test.db s 3 name goofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofygoofy

echo "test: listing db"
$app ./test.db l

echo "test: delete entire db"
$app ./test.db d -1

echo "test: listing db"
$app ./test.db l

echo "test: adding 3 sane rows"
$app ./test.db s 1 kingofmongeese some_email
$app ./test.db s 2 joe new_email
$app ./test.db s 3 frank new_email

echo "test: listing db"
$app ./test.db l

echo "test: delete row 2"
$app ./test.db d 2

echo "test: listing db"
$app ./test.db l